spring:
  application:
    name:
      real_fight_web

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_test/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

    # Log query parameters
    org.hibernate.type: trace

server:
  port: 8081