spring:
  application:
    name:
      real_fight_web

  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jpa_practice_db
    username: user
    password: my-secret-pw
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
